# Project name: TorusSQL.
# Description: Relational database management system.
# Licence: GPL-3.0.
# Author: Alexander (@alkuzin).

# This section defines the toolchain configuration for the project.
[toolchain]
# Stable version of the Rust toolchain.
channel = "stable"